from agent_framework import Agent, Goal, Environment, AgentFunctionCallingActionLanguage, generate_response, register_tool, PythonActionRegistry
import os
from typing import List

    
# Define the agent's goals
goals = [
    Goal(priority=1, name="Gather Information", description="Read each python file in the path where you are being executed in the path './'. "
                                                            "You can use list_project_files action to list all the files in a directory. Then use "
                                                            "read_project_file action to read each one of the files. "
                                                            "make sure that you also read all the files inside all of the subdirectories. "),
    Goal(priority=1, name="Write README", description="When you have read all the files "
                                                    "analyse their content to create the content of a README file that summarizes the project. "
                                                    "make sure that you write the README in a well presented markdown format. "
                                                    "Keep the readme short and concise. "),
    Goal(priority=1, name="Terminate", description="Call the terminate call when you have read all the files "
                                                    "and provide the content of your README in the terminate message")
]

@register_tool(tags=["file_operations", "read"])
def read_project_file(file_name: str) -> str:
    """Reads the content of a file from the specified `file_name`.

    Opens the file in read mode and returns its entire contents as a string.
    Raises FileNotFoundError if the file doesn't exist.
    
    Args:
        file_name: The name of the file to read.
    Returns:
        The content of the file as a string.
    """
    with open(file_name, "r") as f:
        return f.read()

@register_tool(tags=["file_operations", "list"])
def list_project_files(path: str) -> List[str]:
    """Lists all the files and subdirectories in the specified `path`.

    Returns:
        A list of file names and subdirectories in the directory.
    """
    return sorted([file for file in os.listdir(path)])

@register_tool(tags=["system"], terminal=True)
def terminate(message: str) -> str:
    """Terminates the session and prints the readme `message` string to the user.

    Args:
        message: The readme message to print to the user.
    Returns:
        The readme message to print to the user.
    """
    return f"{message}\nTerminating..."

action_registry = PythonActionRegistry(tags=["file_operations", "system"])

# Create an agent instance
agent = Agent(
    goals, 
    AgentFunctionCallingActionLanguage(), 
    action_registry, 
    generate_response=generate_response, 
    environment=Environment()
)


# Run the agent with user input
user_input = "Write a README for this project."
final_memory = agent.run(user_input)

# Print the final README generated by the agent
print("--------------------------------")
print("Final README:")
print(final_memory.get_memories()[-1].get("content"))